config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :contact_us

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  #GET /test_passages/101/result
  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :badges, only: %i[index]

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: %i[index destroy]
    resources :badges
  end
end

app/models/badge.rb
# frozen_string_literal: true

class Badge < ApplicationRecord
  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges

  validates :title, presence: true
  validates :image_url, presence: true
end

app/controllers/admin/badges_controller.rb
# frozen_string_literal: true

require 'fileutils'

class Admin
  class BadgesController < Admin::BaseController
    before_action :find_badge, only: %i[show edit update destroy]
    before_action :dataset, only: %i[new create]

    def index
      @badges = Badge.all
      @user_badges = current_user.badges
    end

    def show
    end

    def new
      @badge = Badge.new
    end

    def edit
    end

    def create
      @badge = Badge.new(badge_params)

      if @badge.save
        redirect_to admin_badge_url(@badge), notice: t('.success')
      else
        render :new
      end
    end

    def update
      if @badge.update(badge_params)
        redirect_to admin_badges_path
      else
        render :edit
      end
    end

    def destroy
      @badge.destroy!

      redirect_to admin_badges_path
    end

    private

    def badge_params
      @badge_params ||= params.require(:badge).permit(:title, :image_url, :rule, :value)
    end

    def find_badge
      @badge = Badge.find(params[:id])
    end

    def dataset
      @rule = {
        'category' => Category.all.pluck(:id, :title),
        'level' => TestsHelper::TEST_LEVELS.values.map { |val| [val, val] },
        'first_try' => []
      }
    end
  end
end

app/controllers/badges_controller.rb
# frozen_string_literal: true

class BadgesController < ApplicationController
  def index
    @badges = current_user.user_badges
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/views/admin/badges/_badge.html.erb
<tr>
  <td class="align-middle">
    <%= content_tag :span, badge.title, class: 'test-title', data: { badge_id: badge.id } %>
  </td>
  <td class="align-middle"><%= image_tag(badge.image_url, size: "80x80") %></td>
  <td class="align-middle"><%= badge.rule %></td>
  <td class="align-middle"><%= badge.value %></td>
  <td class="align-middle"><%= link_to t('admin.badges.index.show'), admin_badge_path(badge) %></td>
  <td class="align-middle">
    <%= link_to t('admin.badges.index.edit'), edit_admin_badge_path(badge) %>
  </td>
  <td class="align-middle">
    <%= link_to t('admin.badges.index.delete'),
                admin_badge_path(badge),
                method: :delete,
                data:   { confirm: "Are you sure?" } %>
  </td>
</tr>

app/views/admin/badges/_form.html.erb
<%= form_with model: [:admin, @badge], local: true do |form| %>
  <%= render 'shared/errors', resource: @badge %>

  <div>Условие выдачи бейджа записывается в поля Rule/Value:
    <p>Примеры:</p>
    <p>rule = "category", value = "Frontend"</p>
    <p>rule = "level", value = "easy"</p>
    <p>rule = "first_try", value = "true"</p>
  </div>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title, id: :badge_title %>
  </p>

  <p>
    <%= form.label :image_url %> <br>
    <%= form.text_field :image_url %>
    <%= @badge.image_url %>
  </p>

  <p>
    <%= form.label :rule %> <br>
    <%= form.text_field :rule, id: :badge_rule_id %>
  </p>

  <p>
    <%= form.label :value %> <br>
    <%= form.text_field :value, id: :badge_value_id %>
  </p>

  <p><%= form.submit %></p>

<% end %>

app/views/admin/badges/edit.html.erb
<h1><%= link_to t('.edit_badge'), @badge.title %></h1>

<%= render 'form' %>
<%= link_to t('.back'), admin_badge_path(@badge) %>

app/views/admin/badges/index.html.erb
<h1><%= t('.header') %></h1>

<p class="new-test">
  <%= link_to t('.new_badge'), new_admin_badge_url %>
</p>

<%= render 'shared/errors', resource: @badge %>

<table class="table">
  <tr>
    <th>
      <%= t('.title') %>
    </th>
    <th>
      <%= t('.image') %>
    </th>
    <th>
      <%= t('.rule') %>
    </th>
    <th>
      <%= t('.value') %>
    </th>
    <th colspan="3"><%= t('.action') %></th>
  </tr>

  <%= render @badges %>

</table>

app/views/admin/badges/new.html.erb
<h1>Create Badge</h1>

<%= render 'form', badge: @badge %>

<%= link_to "Back", admin_badges_path %>

app/views/admin/badges/show.html.erb
<p>
  <strong><%= link_to t('.title') %></strong>
  <%= @badge.title %>
</p>


<p>
  <strong><%= link_to t('.image') %></strong>
  <%= image_tag(@badge.image_url, size: "150x150") %>
<p>


<p>
  <strong><%= link_to t('.rule') %></strong>
    <%= @badge.rule %> 
</p>

<p>
  <strong><%= link_to t('.value') %></strong>
    <%= @badge.value %> 
</p> 

</p>
  <%= link_to t('.edit'), edit_admin_badge_path(@badge) %>
  <%= link_to t('.back'), admin_badges_path %>
</p> 