config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :contact_us

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  #GET /test_passages/101/result
  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :badges, only: %i[index]

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: %i[index destroy]
    resources :badges
  end
end

app/models/admin.rb
class Admin < User

  validates :first_name, presence: true
  validates :last_name, presence: true

end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  belongs_to :question

  scope :correct, -> { where(correct: true) }

  validates :body, presence: true
  validate :validate_answers_amount, on: :create

  private

  def validate_answers_amount
    errors.add(:answers_amount, 'Answers limit reached') if question.answers.count > 4
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
# frozen_string_literal: true

class Badge < ApplicationRecord
  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges

  validates :title, presence: true
  validates :image_url, presence: true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :tests, dependent: :destroy
  has_many :badge_rules, dependent: :destroy

  default_scope { order(title: :asc) }

  validates :title, presence: true
end

app/models/gist.rb
# frozen_string_literal: true

class Gist < ApplicationRecord
  belongs_to :question
  belongs_to :author, class_name: 'User'
end 

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy
  has_many :current_question, class_name: "TestPassage", foreign_key: "current_question_id", dependent: :destroy

  validates :body, presence: true
end

app/models/test.rb
# frozen_string_literal: true

class Test < ApplicationRecord
  POSITIVE_INFINITY = Float::INFINITY

  belongs_to :category
  belongs_to :author, class_name: 'User', foreign_key: :user_id, optional: true

  has_many :questions, dependent: :destroy
  has_many :test_passages
  has_many :users, through: :test_passages
  
  scope :simple, -> { where(level: 0..1) }
  scope :middle, -> { where(level: 2..4) }
  scope :complex, -> { where(level: 5..POSITIVE_INFINITY) }
  scope :sort_by_category, lambda { |category_name|
                              joins(:category)
                              .where(categories: { title: category_name })
                            }
  
  validates :title, presence: true
  validates :level, numericality: { only_integer: true, greater_than: -1 }
  validates :timer, presence: true, numericality: { only_integer: true}

  def self.category_title_with_order(category_name)
    sort_by_category(category_name).order(title: :DESC).pluck(:title)
  end
end

app/models/test_passage.rb
# frozen_string_literal: true

class TestPassage < ApplicationRecord
  SUCCESS_PERCENT = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)

    self.current_question = next_question
    save!
  end

  def passed?
    completed? && success_percentage >= SUCCESS_PERCENT
  end

  def success_percentage
    (self.correct_questions * 100.0 / test.questions.count).round(1)
  end

  def current_question_num
    test.questions.order(:id).where('id <= ?', current_question.id).size
  end

  def get_timer
    self.created_at + self.test.timer * 60 - Time.now
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == Array(answer_ids).map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :confirmable

  has_many :test_passages, dependent: :destroy
  has_many :tests, through: :test_passages
  has_many :created_tests, class_name: "Test", foreign_key: "author_id", dependent: :destroy
  has_many :gists, class_name: "Gist", foreign_key: "author_id", dependent: :destroy
  has_many :user_badges, dependent: :destroy
  has_many :badges, through: :user_badges
  has_many :completed_tests

  def get_tests(level)
    tests.where(level: level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end

  def admin?
    is_a?(Admin)
  end
end

app/models/user_badge.rb
# frozen_string_literal: true

class UserBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/models/user_test.rb
# frozen_string_literal: true

class UserTest < ApplicationRecord
  belongs_to :user
  belongs_to :test
end

app/controllers/tests_controller.rb
# frozen_string_literal: true

class TestsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_test, only: %i[start]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_test_not_found

  def index
    @tests = Test.where(published: true)
  end

  def start
    current_user.tests.push(@test)

    redirect_to current_user.test_passage(@test)
  end

  private

  def find_test
    @test = Test.find(params[:id])
  end

  def rescue_with_test_not_found
    render plain: 'Test was not found'
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_year
    Time.current.year
  end

  def github_url(author, repo)
    link_to 'github', "https://github.com/#{author}/#{repo}", target: '_blank'
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/helpers/gist_helper.rb
module GistHelper
  def gist_hash(html_url)
    html_url.split('/').last
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.persisted?
      "#{I18n.t('admin.questions.edit.edit_question')} #{question.test.title}"
    else
      "#{I18n.t('admin.questions.new.create_question')} #{question.test.title}"
    end
  end
end

app/helpers/tests_helper.rb
module TestsHelper
  TEST_LEVELS = { (0..2) => :easy, (2..4) => :middle, (5..) => :hard }.freeze

  def test_level(test)
    TEST_LEVELS.detect { |level, _| level.include?(test.level) }.last
  end

  def navigation_tests
    link_to "#{I18n.t("navigation.tests")}", tests_path
  end
end

app/views/admin/_nav.html.erb
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
  <span class="navbar-text nav-admin title">
    <%= link_to "TestGuru", root_path, class: 'navbar-brand' %>
    <%= t('header-nav.panel') %>
    <%= link_to t('admin.admin-nav.gists'), admin_gists_path , class: 'nav-link'%>
  </span>

  <span class="navbar-text nav-admin title">
    <%= t('header-nav.greeting') %>, <b><%= current_user.email %></b> Guru |
    <%= link_to t('header-nav.logout'), destroy_user_session_path, method: :delete %>
  </span>

</nav>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.any? %>
<%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do %>
  <h2>
    <%= t('.header', count: resource.errors.count) %>:
  </h2>

  <ul>
    <% resource.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<div>
  <% flash.each do |key, message| %>
    <% if message.present? %>
      <div class="alert alert-danger d-flex align-items-center" role="alert">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
          <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
        </svg>
        <div>
          <%= content_tag :p, message, class: "flash #{key}" %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<footer style="position: absolute;bottom: 0;height: 200px;width: 100%;text-align: center">
  <hr>
  <p class="px-3"> <%= current_year %></p>
  <p class="px-3"><a href="https://thinknetica.com/" target="_blank"><%= t('footer.project')%></a></p>
  <p class="footer_project"><%= link_to t('contact_us.contact_us'), contact_us_path %></p>
  <p class="px-3"><p><%= t('footer.about')%></p><%= github_url('Anna1327', 'Test_Guru') %></p>
</footer>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
  <span>
    <%= link_to t('header-nav.test_guru'), root_path, class: 'navbar-brand' %>
    <% if user_signed_in? %>
      <button type="button" class="btn btn-outline-primary">
      <%= link_to t('header-nav.user_badges'), badges_path, class: 'nav-link' %>
      <% if current_user.admin? %>
        <button type="button" class="btn btn-outline-primary">
          <%= link_to t('header-nav.admin_panel'), admin_tests_path, class: 'nav-link' %>
        </button>
        <button type="button" class="btn btn-outline-primary">
          <%= link_to t('header-nav.admin_badges'), admin_badges_path, class: 'nav-link' %>
        </button>
        <button type="button" class="btn btn-outline-primary">
          <%= link_to t('header-nav.admin_gists'), admin_gists_path, class: 'nav-link' %>
        </button>
      <% end %>
    <% end %>
  </span>
  
  <span class="navbar-text">
    <% if user_signed_in? %>
      <%= t('header-nav.greeting') %>, <b><%= current_user.email %></b> Guru |
      <%= link_to t('header-nav.logout'), destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to t('.log_in'), new_session_path(resource_name) %> |
      <%= link_to t('.sign_up'), new_registration_path(resource_name) %>
    <% end %>
  </span>
</nav>