config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :contact_us

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  #GET /test_passages/101/result
  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :badges, only: %i[index]

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: %i[index destroy]
    resources :badges
  end
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy
  has_many :current_question, class_name: "TestPassage", foreign_key: "current_question_id", dependent: :destroy

  validates :body, presence: true
end

app/models/test_passage.rb
# frozen_string_literal: true

class TestPassage < ApplicationRecord
  SUCCESS_PERCENT = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)

    self.current_question = next_question
    save!
  end

  def passed?
    completed? && success_percentage >= SUCCESS_PERCENT
  end

  def success_percentage
    (self.correct_questions * 100.0 / test.questions.count).round(1)
  end

  def current_question_num
    test.questions.order(:id).where('id <= ?', current_question.id).size
  end

  def get_timer
    self.created_at + self.test.timer * 60 - Time.now
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == Array(answer_ids).map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end
end

app/controllers/test_passages_controller.rb
# frozen_string_literal: true

class TestPassagesController < ApplicationController

  before_action :authenticate_user!
  before_action :find_test_passage, only: %i[show update result gist]

  def show
  end

  def result
  end

  def update
    @test_passage.accept!(params[:answer_ids])
    if @test_passage.completed? || check_time_left
      @test_passage.update!(passed: true) if @test_passage.passed?
      badges = BadgeService.new(@test_passage).check_completed_test
      win_badges_flash(badges.pluck(:title)) unless badges.nil?

      TestsMailer.completed_test(@test_passage).deliver_now
      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end

  def gist
    service = GistQuestionService.new(@test_passage.current_question)
    result = service.call
    if service.success?
      current_user.gists.create(
        url: result.html_url,
        question_id: @test_passage.current_question.id,
        author_id: current_user.id
      )

      flash_options = { notice: t('.success') }
    else
      flash_options = { notice: t('.failure') }
    end
    redirect_to @test_passage, flash_options
  end

  private

  def find_test_passage
    @test_passage = TestPassage.find(params[:id])
  end

  def win_badges_flash(badges)
    flash[:success] = "#{t('test_passages.result.badge_win')}: #{badges.join(',')}!" unless badges.count.zero?
  end

  def check_time_left
    redirect_to result_test_passage_path(@test_passage) if time_left?
  end

  def time_left?
    @test_passage.get_timer <= 0
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
  def current_question
    "Question #{@test_passage.current_question_num} of #{@test_passage.test.questions.count}"
  end
end

app/views/test_passages/_test_passage.html.erb
<h3><%= t('test_passages.result.result') %></h3>
<div>
  <% if @test_passage.passed? %>
    <p><%= t('test_passages.result.success') %><span class="success"> <%= test_passage.success_percentage %>%</span></p>
  <% else %>
    <p><%= t('test_passages.result.failed') %><span class="failed"><%= test_passage.success_percentage %>%</span></p>
  <% end %>
</div>

app/views/test_passages/result.html.erb
<h1><%= t('.header', title: @test_passage.test.title) %></h1>
<%= render @test_passage %>
<%= navigation_tests %>

app/views/test_passages/show.html.erb
<div class="title_container">
  <h1><%= t('.header', title: @test_passage.test.title ) %></h1>
  <div><h6><%= t('helpers.time') %></h6>
    <div class="timer" data-timer="<%= @test_passage.get_timer %>"></div>
  </div>
</div>

<p>
  <b><%= @test_passage.current_question.body %></b>
</p>

<%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |form| %>
  <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: 
  false do |answer| %>
    <p>
      <%= answer.check_box id: "answer_ids_#{answer.object.id}" %>
      <%= answer.label %>
    </p>
  <% end %>

  <p><%= link_to t('.gist'), gist_test_passage_path(@test_passage), method: :post %></p>
  <p><%= form.submit t('helpers.submit.next') %></p>
<% end %>

<div class="mt-3">
  <%= t('.current_question') %>
  <%= @test_passage.current_question_num %>
  <%= t('.of') %>
  <span class="all_questions">
    <%= @test_passage.test.questions.count.to_i %>
  </span>
</div>

<div class="progress-bar-container">
  <div class="progress-bar"
       data-current-test = "<%= @test_passage.current_question %>"
       data-all-tests = "<%= @test_passage.test.questions.count.to_i %>">
    <p class="progress-bar_percent"></p>
  </div>
</div>