config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :contact_us

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  #GET /test_passages/101/result
  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :badges, only: %i[index]

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: %i[index destroy]
    resources :badges
  end
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  belongs_to :question

  scope :correct, -> { where(correct: true) }

  validates :body, presence: true
  validate :validate_answers_amount, on: :create

  private

  def validate_answers_amount
    errors.add(:answers_amount, 'Answers limit reached') if question.answers.count > 4
  end
end

app/controllers/admin/answers_controller.rb
# frozen_string_literal: true

class Admin
  class AnswersController < Admin::BaseController
  
    before_action :find_question, only: %i[new create]
    before_action :find_answer, only: %i[show edit update destroy]
  
    def show
    end
  
    def new
      @answer = @question.answers.new
    end
  
    def edit
    end
  
    def create
      @answer = @question.answers.new(answer_params)
  
      if @answer.save
        redirect_to admin_question_path(@question)
      else
        render :new
      end
    end
  
    def update
      if @answer.update(answer_params)
        redirect_to admin_question_path(@answer.question)
      else
        render :edit
      end
    end
  
    def destroy
      @answer.destroy
      redirect_to admin_question_path(@answer.question)
    end
  
    private
  
    def find_question
      @question = Question.find(params[:question_id])
    end
  
    def find_answer
      @answer = Answer.find(params[:id])
    end
  
    def answer_params
      params.require(:answer).permit(:body, :correct)
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.erb
<li>
  <%= link_to answer.body, answer_path(answer)%> |
  <%= link_to t('navigation.edit'), edit_answer_path(answer) %> |
  <%= link_to t('navigation.delete'), answer_path(answer), method: :delete, data: {confirm: 'Are you sure?'} %>
</li>

app/views/answers/_form.html.erb
<%= form_with model: [@question, @answer], local: true do |form| %>
  <%= render 'shared/errors', resource: @answer %>

  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body, :id :answer_body, rows: 7, cols: 60 %>
  </p>

  <p>
    <%= form.label :correct %><br>
    <%= form.check_box :correct, :id :answer_correct %><br>
  </p>

  <p><%= form.submit %></p>
<% end %>